OUTPUT:
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=1
Clk_in=0	 clk_out=1
Clk_in=1	 clk_out=0
Clk_in=0	 clk_out=0
Clk_in=1	 clk_out=0
