OUTPUT:
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
Clk_in=0	 Clk_out=1
Clk_in=1	 Clk_out=0
Clk_in=0	 Clk_out=0
Clk_in=1	 Clk_out=1
