OUTPUT:
Clk in =0	 Reset=1	 Clk out=0	
Clk in =1	 Reset=1	 Clk out=0	
Clk in =0	 Reset=1	 Clk out=0	
Clk in =1	 Reset=1	 Clk out=0	
Clk in =0	 Reset=1	 Clk out=0	
Clk in =1	 Reset=1	 Clk out=0	
Clk in =0	 Reset=1	 Clk out=0	
Clk in =1	 Reset=1	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=0	
Clk in =0	 Reset=0	 Clk out=0	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1	
Clk in =1	 Reset=0	 Clk out=1	
Clk in =0	 Reset=0	 Clk out=1
